let data = {
    code : 0,
    msg : 'ok',
    data : {
        citylist : [{
            "cityId": 0,
            "cityName": "全国",
            "listName": "qg"
        },{
            "cityId": 20643,
            "cityName": "洛杉矶",
            "listName": "lsj"
        }, {
            "cityId": 5334,
            "cityName": "慈溪",
            "listName": "cx"
        }, {
            "cityId": 6738,
            "cityName": "象山",
            "listName": "xs"
        }, {
            "cityId": 7428,
            "cityName": "金昌",
            "listName": "jc"
        }, {
            "cityId": 10267,
            "cityName": "天长",
            "listName": "tz"
        }, {
            "cityId": 10307,
            "cityName": "白银",
            "listName": "by"
        }, {
            "cityId": 11325,
            "cityName": "沛县",
            "listName": "px"
        }, {
            "cityId": 1,
            "cityName": "北京",
            "listName": "bj"
        }, {
            "cityId": 2,
            "cityName": "上海",
            "listName": "sh"
        }, {
            "cityId": 3,
            "cityName": "广州",
            "listName": "gz"
        }, {
            "cityId": 4,
            "cityName": "深圳",
            "listName": "sz"
        }, {
            "cityId": 293,
            "cityName": "南安",
            "listName": "na"
        }, {
            "cityId": 296,
            "cityName": "石狮",
            "listName": "ss"
        }, {
            "cityId": 297,
            "cityName": "晋江",
            "listName": "jj"
        }, {
            "cityId": 357,
            "cityName": "诸暨",
            "listName": "zj"
        }, {
            "cityId": 369,
            "cityName": "寿光",
            "listName": "sg"
        }, {
            "cityId": 397,
            "cityName": "如皋",
            "listName": "rg"
        }, {
            "cityId": 399,
            "cityName": "海门",
            "listName": "hm"
        }, {
            "cityId": 400,
            "cityName": "启东",
            "listName": "qd"
        }, {
            "cityId": 401,
            "cityName": "海安",
            "listName": "ha"
        }, {
            "cityId": 402,
            "cityName": "如东",
            "listName": "rd"
        }, {
            "cityId": 408,
            "cityName": "温岭",
            "listName": "wl"
        }, {
            "cityId": 469,
            "cityName": "溧阳",
            "listName": "ly"
        }, {
            "cityId": 477,
            "cityName": "邳州",
            "listName": "pz"
        }, {
            "cityId": 478,
            "cityName": "新沂",
            "listName": "xy"
        }, {
            "cityId": 500,
            "cityName": "海宁",
            "listName": "hn"
        }, {
            "cityId": 502,
            "cityName": "桐乡",
            "listName": "tx"
        }, {
            "cityId": 615,
            "cityName": "东台",
            "listName": "dt"
        }, {
            "cityId": 618,
            "cityName": "建湖",
            "listName": "jh"
        }, {
            "cityId": 648,
            "cityName": "丹阳",
            "listName": "dy"
        }, {
            "cityId": 649,
            "cityName": "扬中",
            "listName": "yz"
        }, {
            "cityId": 696,
            "cityName": "泰兴",
            "listName": "tx"
        }, {
            "cityId": 698,
            "cityName": "靖江",
            "listName": "jj"
        }, {
            "cityId": 699,
            "cityName": "兴化",
            "listName": "xh"
        }, {
            "cityId": 725,
            "cityName": "惠东",
            "listName": "hd"
        }, {
            "cityId": 726,
            "cityName": "博罗",
            "listName": "bl"
        }, {
            "cityId": 834,
            "cityName": "长兴",
            "listName": "zx"
        }, {
            "cityId": 835,
            "cityName": "德清",
            "listName": "dq"
        }, {
            "cityId": 864,
            "cityName": "宜都",
            "listName": "yd"
        }, {
            "cityId": 2147,
            "cityName": "东海",
            "listName": "dh"
        }, {
            "cityId": 2284,
            "cityName": "阳江",
            "listName": "yj"
        }, {
            "cityId": 2292,
            "cityName": "莱芜",
            "listName": "lw"
        }, {
            "cityId": 2296,
            "cityName": "荆门",
            "listName": "jm"
        }, {
            "cityId": 2299,
            "cityName": "黄冈",
            "listName": "hg"
        }, {
            "cityId": 2302,
            "cityName": "恩施",
            "listName": "es"
        }, {
            "cityId": 2307,
            "cityName": "永州",
            "listName": "yz"
        }, {
            "cityId": 2315,
            "cityName": "松原",
            "listName": "sy"
        }, {
            "cityId": 2319,
            "cityName": "淮南",
            "listName": "hn"
        }, {
            "cityId": 2323,
            "cityName": "黄山",
            "listName": "hs"
        }, {
            "cityId": 2325,
            "cityName": "阜阳",
            "listName": "fy"
        }, {
            "cityId": 2328,
            "cityName": "六安",
            "listName": "la"
        }, {
            "cityId": 2335,
            "cityName": "钦州",
            "listName": "qz"
        }, {
            "cityId": 2337,
            "cityName": "玉林",
            "listName": "yl"
        }, {
            "cityId": 2340,
            "cityName": "河池",
            "listName": "hc"
        }, {
            "cityId": 2342,
            "cityName": "开封",
            "listName": "kf"
        }, {
            "cityId": 2344,
            "cityName": "鹤壁",
            "listName": "hb"
        }, {
            "cityId": 2354,
            "cityName": "锦州",
            "listName": "jz"
        }, {
            "cityId": 2360,
            "cityName": "景德镇",
            "listName": "jdz"
        }, {
            "cityId": 2363,
            "cityName": "赣州",
            "listName": "gz"
        }, {
            "cityId": 2364,
            "cityName": "吉安",
            "listName": "ja"
        }, {
            "cityId": 2371,
            "cityName": "攀枝花",
            "listName": "pzh"
        }, {
            "cityId": 2372,
            "cityName": "泸州",
            "listName": "lz"
        }, {
            "cityId": 2373,
            "cityName": "德阳",
            "listName": "dy"
        }, {
            "cityId": 2378,
            "cityName": "南充",
            "listName": "nc"
        }, {
            "cityId": 2381,
            "cityName": "广安",
            "listName": "ga"
        }, {
            "cityId": 2389,
            "cityName": "曲靖",
            "listName": "qj"
        }, {
            "cityId": 2392,
            "cityName": "丽江",
            "listName": "lj"
        }, {
            "cityId": 2393,
            "cityName": "楚雄",
            "listName": "cx"
        }, {
            "cityId": 2394,
            "cityName": "红河",
            "listName": "hh"
        }, {
            "cityId": 2395,
            "cityName": "文山",
            "listName": "ws"
        }, {
            "cityId": 2397,
            "cityName": "西双版纳",
            "listName": "xsbn"
        }, {
            "cityId": 2398,
            "cityName": "大理",
            "listName": "dl"
        }, {
            "cityId": 2404,
            "cityName": "乌海",
            "listName": "wh"
        }, {
            "cityId": 2421,
            "cityName": "固原",
            "listName": "gy"
        }, {
            "cityId": 2422,
            "cityName": "三亚",
            "listName": "sy"
        }, {
            "cityId": 14320,
            "cityName": "嘉善",
            "listName": "js"
        }, {
            "cityId": 9545,
            "cityName": "阿拉尔",
            "listName": "ale"
        }, {
            "cityId": 9934,
            "cityName": "海北",
            "listName": "hb"
        }, {
            "cityId": 5645,
            "cityName": "宁国",
            "listName": "ng"
        }, {
            "cityId": 20645,
            "cityName": "旧金山",
            "listName": "jjs"
        }, {
            "cityId": 233,
            "cityName": "龙口",
            "listName": "lk"
        }, {
            "cityId": 979,
            "cityName": "禹州",
            "listName": "yz"
        }, {
            "cityId": 8467,
            "cityName": "天水",
            "listName": "ts"
        }, {
            "cityId": 9690,
            "cityName": "日土",
            "listName": "rt"
        }, {
            "cityId": 20648,
            "cityName": "吉隆坡",
            "listName": "jlp"
        }, {
            "cityId": 79,
            "cityName": "杭州",
            "listName": "hz"
        }, {
            "cityId": 536,
            "cityName": "东阳",
            "listName": "dy"
        }, {
            "cityId": 18,
            "cityName": "天津",
            "listName": "tj"
        }, {
            "cityId": 9692,
            "cityName": "改则",
            "listName": "gz"
        }, {
            "cityId": 158,
            "cityName": "武汉",
            "listName": "wh"
        }, {
            "cityId": 483,
            "cityName": "西安",
            "listName": "xa"
        }, {
            "cityId": 102,
            "cityName": "成都",
            "listName": "cd"
        }, {
            "cityId": 414,
            "cityName": "长沙",
            "listName": "zs"
        }, {
            "cityId": 37,
            "cityName": "重庆",
            "listName": "zq"
        }, {
            "cityId": 172,
            "cityName": "南京",
            "listName": "nj"
        }, {
            "cityId": 5,
            "cityName": "苏州",
            "listName": "sz"
        }, {
            "cityId": 413,
            "cityName": "东莞",
            "listName": "dg"
        }, {
            "cityId": 188,
            "cityName": "沈阳",
            "listName": "sy"
        }, {
            "cityId": 304,
            "cityName": "福州",
            "listName": "fz"
        }, {
            "cityId": 606,
            "cityName": "厦门",
            "listName": "sm"
        }, {
            "cityId": 265,
            "cityName": "济南",
            "listName": "jn"
        }, {
            "cityId": 669,
            "cityName": "南昌",
            "listName": "nc"
        }, {
            "cityId": 319,
            "cityName": "长春",
            "listName": "zc"
        }, {
            "cityId": 222,
            "cityName": "佛山",
            "listName": "fs"
        }, {
            "cityId": 342,
            "cityName": "郑州",
            "listName": "zz"
        }, {
            "cityId": 93,
            "cityName": "无锡",
            "listName": "wx"
        }, {
            "cityId": 122,
            "cityName": "青岛",
            "listName": "qd"
        }, {
            "cityId": 202,
            "cityName": "哈尔滨",
            "listName": "heb"
        }, {
            "cityId": 241,
            "cityName": "石家庄",
            "listName": "sjz"
        }, {
            "cityId": 147,
            "cityName": "大连",
            "listName": "dl"
        }, {
            "cityId": 2053,
            "cityName": "海口",
            "listName": "hk"
        }, {
            "cityId": 135,
            "cityName": "宁波",
            "listName": "nb"
        }, {
            "cityId": 20672,
            "cityName": "新加坡",
            "listName": "xjp"
        }, {
            "cityId": 228,
            "cityName": "烟台",
            "listName": "yt"
        }, {
            "cityId": 20673,
            "cityName": "纽约",
            "listName": "ny"
        }, {
            "cityId": 20674,
            "cityName": "曼谷",
            "listName": "mg"
        }, {
            "cityId": 837,
            "cityName": "合肥",
            "listName": "hf"
        }, {
            "cityId": 362,
            "cityName": "潍坊",
            "listName": "wf"
        }, {
            "cityId": 20675,
            "cityName": "悉尼",
            "listName": "xn"
        }, {
            "cityId": 845,
            "cityName": "南宁",
            "listName": "nn"
        }, {
            "cityId": 20676,
            "cityName": "墨尔本",
            "listName": "meb"
        }, {
            "cityId": 291,
            "cityName": "泉州",
            "listName": "qz"
        }, {
            "cityId": 20677,
            "cityName": "芝加哥",
            "listName": "zjg"
        }, {
            "cityId": 20678,
            "cityName": "圣地亚哥",
            "listName": "sdyg"
        }, {
            "cityId": 984,
            "cityName": "乌鲁木齐",
            "listName": "wlmq"
        }, {
            "cityId": 20679,
            "cityName": "拉斯维加斯",
            "listName": "lswjs"
        }, {
            "cityId": 910,
            "cityName": "珠海",
            "listName": "zh"
        }, {
            "cityId": 952,
            "cityName": "兰州",
            "listName": "lz"
        }, {
            "cityId": 20680,
            "cityName": "多伦多",
            "listName": "dld"
        }, {
            "cityId": 541,
            "cityName": "昆明",
            "listName": "km"
        }, {
            "cityId": 20681,
            "cityName": "温哥华",
            "listName": "wgh"
        }, {
            "cityId": 20682,
            "cityName": "蒙特利尔",
            "listName": "mtle"
        }, {
            "cityId": 740,
            "cityName": "太原",
            "listName": "ty"
        }, {
            "cityId": 3328,
            "cityName": "张家口",
            "listName": "zjk"
        }, {
            "cityId": 783,
            "cityName": "汕头",
            "listName": "st"
        }, {
            "cityId": 771,
            "cityName": "中山",
            "listName": "zs"
        }, {
            "cityId": 811,
            "cityName": "呼和浩特",
            "listName": "hhht"
        }, {
            "cityId": 330,
            "cityName": "温州",
            "listName": "wz"
        }, {
            "cityId": 523,
            "cityName": "鞍山",
            "listName": "as"
        }, {
            "cityId": 450,
            "cityName": "济宁",
            "listName": "jn"
        }, {
            "cityId": 497,
            "cityName": "嘉兴",
            "listName": "jx"
        }, {
            "cityId": 463,
            "cityName": "常州",
            "listName": "cz"
        }, {
            "cityId": 276,
            "cityName": "唐山",
            "listName": "ts"
        }, {
            "cityId": 1057,
            "cityName": "绵阳",
            "listName": "my"
        }, {
            "cityId": 22584,
            "cityName": "伦敦",
            "listName": "ld"
        }, {
            "cityId": 424,
            "cityName": "保定",
            "listName": "bd"
        }, {
            "cityId": 23275,
            "cityName": "东京",
            "listName": "dj"
        }, {
            "cityId": 722,
            "cityName": "惠州",
            "listName": "hz"
        }, {
            "cityId": 23301,
            "cityName": "首尔",
            "listName": "se"
        }, {
            "cityId": 23862,
            "cityName": "檀香山",
            "listName": "txs"
        }, {
            "cityId": 518,
            "cityName": "威海",
            "listName": "wh"
        }, {
            "cityId": 23863,
            "cityName": "华盛顿",
            "listName": "hsd"
        }, {
            "cityId": 629,
            "cityName": "江门",
            "listName": "jm"
        }, {
            "cityId": 23864,
            "cityName": "西雅图",
            "listName": "xyt"
        }, {
            "cityId": 385,
            "cityName": "淄博",
            "listName": "zb"
        }, {
            "cityId": 23865,
            "cityName": "休斯顿",
            "listName": "xsd"
        }, {
            "cityId": 556,
            "cityName": "洛阳",
            "listName": "ly"
        }, {
            "cityId": 23866,
            "cityName": "费城",
            "listName": "fc"
        }, {
            "cityId": 1086,
            "cityName": "株洲",
            "listName": "zz"
        }, {
            "cityId": 3359,
            "cityName": "宿州",
            "listName": "sz"
        }, {
            "cityId": 23867,
            "cityName": "波士顿",
            "listName": "bsd"
        }, {
            "cityId": 914,
            "cityName": "衡阳",
            "listName": "hy"
        }, {
            "cityId": 23381,
            "cityName": "渥太华",
            "listName": "wth"
        }, {
            "cityId": 23868,
            "cityName": "卡尔加里",
            "listName": "kejl"
        }, {
            "cityId": 2015,
            "cityName": "贵阳",
            "listName": "gy"
        }, {
            "cityId": 728,
            "cityName": "德州",
            "listName": "dz"
        }, {
            "cityId": 23869,
            "cityName": "巴黎",
            "listName": "bl"
        }, {
            "cityId": 23870,
            "cityName": "米兰",
            "listName": "ml"
        }, {
            "cityId": 531,
            "cityName": "金华",
            "listName": "jh"
        }, {
            "cityId": 700,
            "cityName": "吉林",
            "listName": "jl"
        }, {
            "cityId": 23871,
            "cityName": "柏林",
            "listName": "bl"
        }, {
            "cityId": 23872,
            "cityName": "巴塞罗那",
            "listName": "bsln"
        }, {
            "cityId": 801,
            "cityName": "包头",
            "listName": "bt"
        }, {
            "cityId": 23873,
            "cityName": "马德里",
            "listName": "mdl"
        }, {
            "cityId": 652,
            "cityName": "沧州",
            "listName": "cz"
        }, {
            "cityId": 592,
            "cityName": "南阳",
            "listName": "ny"
        }, {
            "cityId": 23874,
            "cityName": "莫斯科",
            "listName": "msk"
        }, {
            "cityId": 23875,
            "cityName": "堪培拉",
            "listName": "kpl"
        }, {
            "cityId": 772,
            "cityName": "廊坊",
            "listName": "lf"
        }, {
            "cityId": 23876,
            "cityName": "布里斯班",
            "listName": "blsb"
        }, {
            "cityId": 944,
            "cityName": "滨州",
            "listName": "bz"
        }, {
            "cityId": 1078,
            "cityName": "秦皇岛",
            "listName": "qhd"
        }, {
            "cityId": 23877,
            "cityName": "惠灵顿",
            "listName": "hld"
        }, {
            "cityId": 23878,
            "cityName": "奥克兰",
            "listName": "akl"
        }, {
            "cityId": 18804,
            "cityName": "阿勒泰",
            "listName": "alt"
        }, {
            "cityId": 18812,
            "cityName": "塔城",
            "listName": "tc"
        }, {
            "cityId": 3177,
            "cityName": "日照",
            "listName": "rz"
        }, {
            "cityId": 24510,
            "cityName": "清迈",
            "listName": "qm"
        }, {
            "cityId": 471,
            "cityName": "徐州",
            "listName": "xz"
        }, {
            "cityId": 623,
            "cityName": "东营",
            "listName": "dy"
        }, {
            "cityId": 5333,
            "cityName": "余姚",
            "listName": "yy"
        }, {
            "cityId": 24650,
            "cityName": "迪拜",
            "listName": "db"
        }, {
            "cityId": 686,
            "cityName": "泰安",
            "listName": "ta"
        }, {
            "cityId": 505,
            "cityName": "临沂",
            "listName": "ly"
        }, {
            "cityId": 1096,
            "cityName": "安阳",
            "listName": "ay"
        }, {
            "cityId": 403,
            "cityName": "台州",
            "listName": "tz"
        }, {
            "cityId": 637,
            "cityName": "扬州",
            "listName": "yz"
        }, {
            "cityId": 394,
            "cityName": "南通",
            "listName": "nt"
        }, {
            "cityId": 710,
            "cityName": "漳州",
            "listName": "zz"
        }, {
            "cityId": 572,
            "cityName": "邯郸",
            "listName": "hd"
        }, {
            "cityId": 927,
            "cityName": "揭阳",
            "listName": "jy"
        }, {
            "cityId": 882,
            "cityName": "聊城",
            "listName": "lc"
        }, {
            "cityId": 1005,
            "cityName": "平顶山",
            "listName": "pds"
        }, {
            "cityId": 2044,
            "cityName": "宝鸡",
            "listName": "bj"
        }, {
            "cityId": 355,
            "cityName": "绍兴",
            "listName": "sx"
        }, {
            "cityId": 375,
            "cityName": "大庆",
            "listName": "dq"
        }, {
            "cityId": 679,
            "cityName": "茂名",
            "listName": "mm"
        }, {
            "cityId": 2049,
            "cityName": "连云港",
            "listName": "lyg"
        }, {
            "cityId": 831,
            "cityName": "湖州",
            "listName": "hz"
        }, {
            "cityId": 2047,
            "cityName": "湘潭",
            "listName": "xt"
        }, {
            "cityId": 1039,
            "cityName": "桂林",
            "listName": "gl"
        }, {
            "cityId": 791,
            "cityName": "湛江",
            "listName": "zj"
        }, {
            "cityId": 858,
            "cityName": "宜昌",
            "listName": "yc"
        }, {
            "cityId": 901,
            "cityName": "肇庆",
            "listName": "zq"
        }, {
            "cityId": 891,
            "cityName": "襄阳",
            "listName": "xy"
        }, {
            "cityId": 961,
            "cityName": "枣庄",
            "listName": "zz"
        }, {
            "cityId": 613,
            "cityName": "盐城",
            "listName": "yc"
        }, {
            "cityId": 2032,
            "cityName": "十堰",
            "listName": "sy"
        }, {
            "cityId": 821,
            "cityName": "岳阳",
            "listName": "yy"
        }, {
            "cityId": 993,
            "cityName": "衡水",
            "listName": "hs"
        }, {
            "cityId": 1016,
            "cityName": "新乡",
            "listName": "xx"
        }, {
            "cityId": 2258,
            "cityName": "其他",
            "listName": "qt"
        }, {
            "cityId": 7923,
            "cityName": "丽水",
            "listName": "ls"
        }, {
            "cityId": 7969,
            "cityName": "宁德",
            "listName": "nd"
        }, {
            "cityId": 8408,
            "cityName": "定州",
            "listName": "dz"
        }, {
            "cityId": 8470,
            "cityName": "舟山",
            "listName": "zs"
        }, {
            "cityId": 8531,
            "cityName": "明港",
            "listName": "mg"
        }, {
            "cityId": 8556,
            "cityName": "阳春",
            "listName": "yc"
        }, {
            "cityId": 8572,
            "cityName": "昌吉",
            "listName": "cj"
        }, {
            "cityId": 8658,
            "cityName": "章丘",
            "listName": "zq"
        }, {
            "cityId": 8672,
            "cityName": "信阳",
            "listName": "xy"
        }, {
            "cityId": 8684,
            "cityName": "馆陶",
            "listName": "gt"
        }, {
            "cityId": 8694,
            "cityName": "顺德",
            "listName": "sd"
        },  {
            "cityId": 8738,
            "cityName": "阳泉",
            "listName": "yq"
        }, {
            "cityId": 8832,
            "cityName": "晋中",
            "listName": "jz"
        }, {
            "cityId": 8951,
            "cityName": "延安",
            "listName": "ya"
        }, {
            "cityId": 9026,
            "cityName": "赵县",
            "listName": "zx"
        }, {
            "cityId": 9039,
            "cityName": "鹤岗",
            "listName": "hg"
        }, {
            "cityId": 9101,
            "cityName": "鄢陵",
            "listName": "yl"
        }, {
            "cityId": 9124,
            "cityName": "诸城",
            "listName": "zc"
        }, {
            "cityId": 9179,
            "cityName": "临猗",
            "listName": "ly"
        }, {
            "cityId": 9303,
            "cityName": "三门峡",
            "listName": "smx"
        }, {
            "cityId": 9455,
            "cityName": "娄底",
            "listName": "ld"
        }, {
            "cityId": 9702,
            "cityName": "鄂州",
            "listName": "ez"
        }, {
            "cityId": 9723,
            "cityName": "仙桃",
            "listName": "xt"
        }, {
            "cityId": 9765,
            "cityName": "伊春",
            "listName": "yc"
        }, {
            "cityId": 9836,
            "cityName": "双鸭山",
            "listName": "sys"
        }, {
            "cityId": 9846,
            "cityName": "七台河",
            "listName": "qth"
        }, {
            "cityId": 9858,
            "cityName": "黑河",
            "listName": "hh"
        }, {
            "cityId": 9875,
            "cityName": "大兴安岭",
            "listName": "dxal"
        }, {
            "cityId": 9894,
            "cityName": "济源",
            "listName": "jy"
        }, {
            "cityId": 9948,
            "cityName": "五指山",
            "listName": "wzs"
        }, {
            "cityId": 7452,
            "cityName": "哈密",
            "listName": "hm"
        }, {
            "cityId": 7453,
            "cityName": "咸阳",
            "listName": "xy"
        }, {
            "cityId": 7624,
            "cityName": "遵义",
            "listName": "zy"
        }, {
            "cityId": 13663,
            "cityName": "三沙",
            "listName": "ss"
        }, {
            "cityId": 13895,
            "cityName": "乐清",
            "listName": "lq"
        }, {
            "cityId": 13894,
            "cityName": "瑞安",
            "listName": "ra"
        }, {
            "cityId": 9968,
            "cityName": "文昌",
            "listName": "wc"
        }, {
            "cityId": 10011,
            "cityName": "万宁",
            "listName": "wn"
        }, {
            "cityId": 10049,
            "cityName": "屯昌",
            "listName": "tc"
        }, {
            "cityId": 10130,
            "cityName": "琼海",
            "listName": "qh"
        }, {
            "cityId": 10166,
            "cityName": "陵水",
            "listName": "ls"
        }, {
            "cityId": 10244,
            "cityName": "东方",
            "listName": "df"
        }, {
            "cityId": 10297,
            "cityName": "定安",
            "listName": "da"
        }, {
            "cityId": 10316,
            "cityName": "澄迈",
            "listName": "cm"
        }, {
            "cityId": 10367,
            "cityName": "保亭",
            "listName": "bt"
        }, {
            "cityId": 10375,
            "cityName": "白沙",
            "listName": "bs"
        }, {
            "cityId": 10390,
            "cityName": "儋州",
            "listName": "dz"
        }, {
            "cityId": 10419,
            "cityName": "铜仁",
            "listName": "tr"
        }, {
            "cityId": 10430,
            "cityName": "黔西南",
            "listName": "qxn"
        }, {
            "cityId": 10441,
            "cityName": "黔南",
            "listName": "qn"
        }, {
            "cityId": 10500,
            "cityName": "六盘水",
            "listName": "lps"
        }, {
            "cityId": 2045,
            "cityName": "芜湖",
            "listName": "wh"
        }, {
            "cityId": 751,
            "cityName": "邢台",
            "listName": "xt"
        }, {
            "cityId": 2247,
            "cityName": "九江",
            "listName": "jj"
        }, {
            "cityId": 3434,
            "cityName": "孝感",
            "listName": "xg"
        }, {
            "cityId": 3222,
            "cityName": "吕梁",
            "listName": "ll"
        }, {
            "cityId": 693,
            "cityName": "泰州",
            "listName": "tz"
        }, {
            "cityId": 2052,
            "cityName": "西宁",
            "listName": "xn"
        }, {
            "cityId": 2048,
            "cityName": "三明",
            "listName": "sm"
        }, {
            "cityId": 2192,
            "cityName": "韶关",
            "listName": "sg"
        }, {
            "cityId": 3266,
            "cityName": "焦作",
            "listName": "jz"
        }, {
            "cityId": 6700,
            "cityName": "赤峰",
            "listName": "cf"
        }, {
            "cityId": 872,
            "cityName": "常德",
            "listName": "cd"
        }, {
            "cityId": 3237,
            "cityName": "乐山",
            "listName": "ls"
        }, {
            "cityId": 3163,
            "cityName": "汉中",
            "listName": "hz"
        }, {
            "cityId": 645,
            "cityName": "镇江",
            "listName": "zj"
        }, {
            "cityId": 2054,
            "cityName": "银川",
            "listName": "yc"
        }, {
            "cityId": 2037,
            "cityName": "鄂尔多斯",
            "listName": "eeds"
        }, {
            "cityId": 3184,
            "cityName": "延边",
            "listName": "yb"
        }, {
            "cityId": 977,
            "cityName": "许昌",
            "listName": "xc"
        }, {
            "cityId": 1029,
            "cityName": "商丘",
            "listName": "sq"
        }, {
            "cityId": 933,
            "cityName": "周口",
            "listName": "zk"
        }, {
            "cityId": 3350,
            "cityName": "晋城",
            "listName": "jc"
        }, {
            "cityId": 3251,
            "cityName": "安庆",
            "listName": "aq"
        }, {
            "cityId": 968,
            "cityName": "淮安",
            "listName": "ha"
        }, {
            "cityId": 2038,
            "cityName": "辽阳",
            "listName": "ly"
        }, {
            "cityId": 3198,
            "cityName": "正定",
            "listName": "zd"
        }, {
            "cityId": 2042,
            "cityName": "克拉玛依",
            "listName": "klmy"
        }, {
            "cityId": 2046,
            "cityName": "梧州",
            "listName": "wz"
        }, {
            "cityId": 1067,
            "cityName": "驻马店",
            "listName": "zmd"
        }, {
            "cityId": 2039,
            "cityName": "马鞍山",
            "listName": "mas"
        }, {
            "cityId": 1734,
            "cityName": "黄石",
            "listName": "hs"
        }, {
            "cityId": 2041,
            "cityName": "盘锦",
            "listName": "pj"
        }, {
            "cityId": 2248,
            "cityName": "萍乡",
            "listName": "px"
        }, {
            "cityId": 3157,
            "cityName": "安康",
            "listName": "ak"
        }, {
            "cityId": 2050,
            "cityName": "香港",
            "listName": "xg"
        }, {
            "cityId": 3209,
            "cityName": "鹰潭",
            "listName": "yt"
        }, {
            "cityId": 3445,
            "cityName": "丹东",
            "listName": "dd"
        }, {
            "cityId": 2501,
            "cityName": "辽源",
            "listName": "ly"
        }, {
            "cityId": 2055,
            "cityName": "拉萨",
            "listName": "ls"
        }, {
            "cityId": 2043,
            "cityName": "海拉尔",
            "listName": "hle"
        }, {
            "cityId": 2040,
            "cityName": "玉溪",
            "listName": "yx"
        }, {
            "cityId": 2051,
            "cityName": "台湾",
            "listName": "tw"
        }, {
            "cityId": 3279,
            "cityName": "瓦房店",
            "listName": "wfd"
        }, {
            "cityId": 3306,
            "cityName": "庄河",
            "listName": "zh"
        }, {
            "cityId": 3453,
            "cityName": "忻州",
            "listName": "xz"
        }, {
            "cityId": 3470,
            "cityName": "蚌埠",
            "listName": "bb"
        }, {
            "cityId": 3479,
            "cityName": "荆州",
            "listName": "jz"
        }, {
            "cityId": 3489,
            "cityName": "牡丹江",
            "listName": "mdj"
        }, {
            "cityId": 5632,
            "cityName": "菏泽",
            "listName": "hz"
        }, {
            "cityId": 5633,
            "cityName": "宣城",
            "listName": "xc"
        }, {
            "cityId": 5653,
            "cityName": "运城",
            "listName": "yc"
        }, {
            "cityId": 5669,
            "cityName": "临汾",
            "listName": "lf"
        }, {
            "cityId": 5695,
            "cityName": "郴州",
            "listName": "cz"
        }, {
            "cityId": 5709,
            "cityName": "宜春",
            "listName": "yc"
        }, {
            "cityId": 5722,
            "cityName": "抚顺",
            "listName": "fs"
        }, {
            "cityId": 5733,
            "cityName": "渭南",
            "listName": "wn"
        }, {
            "cityId": 5756,
            "cityName": "怀化",
            "listName": "hh"
        }, {
            "cityId": 5772,
            "cityName": "沭阳",
            "listName": "sy"
        }, {
            "cityId": 5845,
            "cityName": "本溪",
            "listName": "bx"
        }, {
            "cityId": 5853,
            "cityName": "齐齐哈尔",
            "listName": "qqhe"
        }, {
            "cityId": 5898,
            "cityName": "营口",
            "listName": "yk"
        }, {
            "cityId": 5918,
            "cityName": "白城",
            "listName": "bc"
        }, {
            "cityId": 5928,
            "cityName": "内江",
            "listName": "nj"
        }, {
            "cityId": 5942,
            "cityName": "榆林",
            "listName": "yl"
        }, {
            "cityId": 2350,
            "cityName": "宿迁",
            "listName": "sq"
        }, {
            "cityId": 6718,
            "cityName": "绥化",
            "listName": "sh"
        }, {
            "cityId": 6729,
            "cityName": "铁岭",
            "listName": "tl"
        }, {
            "cityId": 6745,
            "cityName": "自贡",
            "listName": "zg"
        }, {
            "cityId": 6752,
            "cityName": "龙岩",
            "listName": "ly"
        }, {
            "cityId": 6760,
            "cityName": "承德",
            "listName": "cd"
        }, {
            "cityId": 6770,
            "cityName": "贵港",
            "listName": "gg"
        }, {
            "cityId": 6776,
            "cityName": "佳木斯",
            "listName": "jms"
        }, {
            "cityId": 6788,
            "cityName": "张家界",
            "listName": "zjj"
        }, {
            "cityId": 6793,
            "cityName": "衢州",
            "listName": "qz"
        }, {
            "cityId": 6803,
            "cityName": "资阳",
            "listName": "zy"
        }, {
            "cityId": 6921,
            "cityName": "长治",
            "listName": "zz"
        }, {
            "cityId": 6964,
            "cityName": "大同",
            "listName": "dt"
        }, {
            "cityId": 2303,
            "cityName": "邵阳",
            "listName": "sy"
        }, {
            "cityId": 2329,
            "cityName": "亳州",
            "listName": "bz"
        }, {
            "cityId": 2390,
            "cityName": "保山",
            "listName": "bs"
        }, {
            "cityId": 7112,
            "cityName": "临夏",
            "listName": "lx"
        }, {
            "cityId": 2380,
            "cityName": "宜宾",
            "listName": "yb"
        }, {
            "cityId": 7133,
            "cityName": "柳州",
            "listName": "lz"
        }, {
            "cityId": 7154,
            "cityName": "平凉",
            "listName": "pl"
        }, {
            "cityId": 2347,
            "cityName": "漯河",
            "listName": "lh"
        }, {
            "cityId": 2346,
            "cityName": "濮阳",
            "listName": "py"
        }, {
            "cityId": 7289,
            "cityName": "鸡西",
            "listName": "jx"
        }, {
            "cityId": 7303,
            "cityName": "清远",
            "listName": "qy"
        }, {
            "cityId": 2429,
            "cityName": "莆田",
            "listName": "pt"
        }, {
            "cityId": 9311,
            "cityName": "喀什",
            "listName": "ks"
        }, {
            "cityId": 9342,
            "cityName": "淮北",
            "listName": "hb"
        }, {
            "cityId": 9329,
            "cityName": "长葛",
            "listName": "zg"
        }, {
            "cityId": 9348,
            "cityName": "黔东南",
            "listName": "qdn"
        }, {
            "cityId": 9374,
            "cityName": "梅州",
            "listName": "mz"
        }, {
            "cityId": 9384,
            "cityName": "澳门",
            "listName": "am"
        }, {
            "cityId": 9394,
            "cityName": "昭通",
            "listName": "zt"
        }, {
            "cityId": 9407,
            "cityName": "临沧",
            "listName": "lc"
        }, {
            "cityId": 9417,
            "cityName": "迪庆",
            "listName": "dq"
        }, {
            "cityId": 9422,
            "cityName": "德宏",
            "listName": "dh"
        }, {
            "cityId": 9429,
            "cityName": "普洱",
            "listName": "pe"
        }, {
            "cityId": 9452,
            "cityName": "怒江",
            "listName": "nj"
        }, {
            "cityId": 9441,
            "cityName": "汕尾",
            "listName": "sw"
        }, {
            "cityId": 9464,
            "cityName": "吐鲁番",
            "listName": "tlf"
        }, {
            "cityId": 10060,
            "cityName": "琼中",
            "listName": "qz"
        }, {
            "cityId": 9486,
            "cityName": "和田",
            "listName": "ht"
        }, {
            "cityId": 9510,
            "cityName": "阿克苏",
            "listName": "aks"
        }, {
            "cityId": 9527,
            "cityName": "克孜勒苏",
            "listName": "kzls"
        }, {
            "cityId": 9533,
            "cityName": "巴音郭楞",
            "listName": "bygl"
        }, {
            "cityId": 9564,
            "cityName": "五家渠",
            "listName": "wjq"
        }, {
            "cityId": 9587,
            "cityName": "日喀则",
            "listName": "rkz"
        }, {
            "cityId": 9636,
            "cityName": "昌都",
            "listName": "cd"
        }, {
            "cityId": 9676,
            "cityName": "雅安",
            "listName": "ya"
        }, {
            "cityId": 9704,
            "cityName": "眉山",
            "listName": "ms"
        }, {
            "cityId": 9715,
            "cityName": "凉山",
            "listName": "ls"
        }, {
            "cityId": 9751,
            "cityName": "广元",
            "listName": "gy"
        }, {
            "cityId": 9760,
            "cityName": "甘孜",
            "listName": "gz"
        }, {
            "cityId": 9799,
            "cityName": "达州",
            "listName": "dz"
        }, {
            "cityId": 9808,
            "cityName": "巴中",
            "listName": "bz"
        }, {
            "cityId": 9814,
            "cityName": "阿坝",
            "listName": "ab"
        }, {
            "cityId": 9829,
            "cityName": "铜川",
            "listName": "tc"
        }, {
            "cityId": 9851,
            "cityName": "商洛",
            "listName": "sl"
        }, {
            "cityId": 9869,
            "cityName": "朔州",
            "listName": "sz"
        }, {
            "cityId": 9886,
            "cityName": "玉树",
            "listName": "ys"
        }, {
            "cityId": 9465,
            "cityName": "伊犁",
            "listName": "yl"
        }, {
            "cityId": 9896,
            "cityName": "黄南",
            "listName": "hn"
        }, {
            "cityId": 9539,
            "cityName": "博尔塔拉",
            "listName": "betl"
        }, {
            "cityId": 9905,
            "cityName": "海西",
            "listName": "hx"
        }, {
            "cityId": 9921,
            "cityName": "海东",
            "listName": "hd"
        }, {
            "cityId": 9940,
            "cityName": "果洛",
            "listName": "gl"
        }, {
            "cityId": 9949,
            "cityName": "中卫",
            "listName": "zw"
        }, {
            "cityId": 9556,
            "cityName": "石河子",
            "listName": "shz"
        }, {
            "cityId": 9959,
            "cityName": "吴忠",
            "listName": "wz"
        }, {
            "cityId": 9967,
            "cityName": "石嘴山",
            "listName": "szs"
        }, {
            "cityId": 9983,
            "cityName": "兴安盟",
            "listName": "xam"
        }, {
            "cityId": 9563,
            "cityName": "图木舒克",
            "listName": "tmsk"
        }, {
            "cityId": 9625,
            "cityName": "那曲",
            "listName": "nq"
        }, {
            "cityId": 9578,
            "cityName": "山南",
            "listName": "sn"
        }, {
            "cityId": 9998,
            "cityName": "乌兰察布",
            "listName": "wlcb"
        }, {
            "cityId": 10012,
            "cityName": "通辽",
            "listName": "tl"
        }, {
            "cityId": 9635,
            "cityName": "林芝",
            "listName": "lz"
        }, {
            "cityId": 9686,
            "cityName": "阿里",
            "listName": "al"
        }, {
            "cityId": 10035,
            "cityName": "呼伦贝尔",
            "listName": "hlbe"
        }, {
            "cityId": 10063,
            "cityName": "巴彦淖尔市",
            "listName": "bynes"
        }, {
            "cityId": 9695,
            "cityName": "遂宁",
            "listName": "sn"
        }, {
            "cityId": 10078,
            "cityName": "阿拉善盟",
            "listName": "alsm"
        }, {
            "cityId": 10083,
            "cityName": "葫芦岛",
            "listName": "hld"
        }, {
            "cityId": 10093,
            "cityName": "阜新",
            "listName": "fx"
        }, {
            "cityId": 10102,
            "cityName": "朝阳",
            "listName": "cy"
        }, {
            "cityId": 10111,
            "cityName": "新余",
            "listName": "xy"
        }, {
            "cityId": 10116,
            "cityName": "上饶",
            "listName": "sr"
        }, {
            "cityId": 10138,
            "cityName": "抚州",
            "listName": "fz"
        }, {
            "cityId": 10157,
            "cityName": "通化",
            "listName": "th"
        }, {
            "cityId": 10167,
            "cityName": "四平",
            "listName": "sp"
        }, {
            "cityId": 10177,
            "cityName": "白山",
            "listName": "bs"
        }, {
            "cityId": 10193,
            "cityName": "益阳",
            "listName": "yy"
        }, {
            "cityId": 10214,
            "cityName": "湘西",
            "listName": "xx"
        }, {
            "cityId": 10224,
            "cityName": "巢湖",
            "listName": "ch"
        }, {
            "cityId": 10254,
            "cityName": "池州",
            "listName": "cz"
        }, {
            "cityId": 10260,
            "cityName": "滁州",
            "listName": "cz"
        }, {
            "cityId": 10279,
            "cityName": "铜陵",
            "listName": "tl"
        }, {
            "cityId": 10285,
            "cityName": "南平",
            "listName": "np"
        }, {
            "cityId": 10320,
            "cityName": "定西",
            "listName": "dx"
        }, {
            "cityId": 10337,
            "cityName": "甘南",
            "listName": "gn"
        }, {
            "cityId": 10356,
            "cityName": "嘉峪关",
            "listName": "jyg"
        }, {
            "cityId": 10381,
            "cityName": "酒泉",
            "listName": "jq"
        }, {
            "cityId": 10409,
            "cityName": "陇南",
            "listName": "ln"
        }, {
            "cityId": 10443,
            "cityName": "武威",
            "listName": "ww"
        }, {
            "cityId": 10449,
            "cityName": "张掖",
            "listName": "zy"
        }, {
            "cityId": 10456,
            "cityName": "潮州",
            "listName": "cz"
        }, {
            "cityId": 10462,
            "cityName": "河源",
            "listName": "hy"
        }, {
            "cityId": 10470,
            "cityName": "庆阳",
            "listName": "qy"
        }, {
            "cityId": 10480,
            "cityName": "云浮",
            "listName": "yf"
        }, {
            "cityId": 10514,
            "cityName": "崇左",
            "listName": "cz"
        }, {
            "cityId": 10530,
            "cityName": "防城港",
            "listName": "fcg"
        }, {
            "cityId": 10541,
            "cityName": "贺州",
            "listName": "hz"
        }, {
            "cityId": 10553,
            "cityName": "毕节",
            "listName": "bj"
        }, {
            "cityId": 10506,
            "cityName": "百色",
            "listName": "bs"
        }, {
            "cityId": 10510,
            "cityName": "北海",
            "listName": "bh"
        }, {
            "cityId": 10549,
            "cityName": "来宾",
            "listName": "lb"
        }, {
            "cityId": 10567,
            "cityName": "海南",
            "listName": "hn"
        }, {
            "cityId": 10737,
            "cityName": "武夷山",
            "listName": "wys"
        }, {
            "cityId": 10868,
            "cityName": "和县",
            "listName": "hx"
        }, {
            "cityId": 10884,
            "cityName": "清徐",
            "listName": "qx"
        }, {
            "cityId": 11053,
            "cityName": "永新",
            "listName": "yx"
        }, {
            "cityId": 9655,
            "cityName": "潜江",
            "listName": "qj"
        }, {
            "cityId": 9616,
            "cityName": "咸宁",
            "listName": "xn"
        }, {
            "cityId": 9630,
            "cityName": "随州",
            "listName": "sz"
        }, {
            "cityId": 9597,
            "cityName": "神农架",
            "listName": "snj"
        }, {
            "cityId": 9475,
            "cityName": "天门",
            "listName": "tm"
        }, {
            "cityId": 2408,
            "cityName": "锡林郭勒",
            "listName": "xlgl"
        }, {
            "cityId": 7458,
            "cityName": "安顺",
            "listName": "as"
        }, {
            "cityId": 11176,
            "cityName": "张北",
            "listName": "zb"
        }, {
            "cityId": 11201,
            "cityName": "霍邱",
            "listName": "hq"
        }, {
            "cityId": 11238,
            "cityName": "台山",
            "listName": "ts"
        }, {
            "cityId": 11254,
            "cityName": "大丰",
            "listName": "df"
        }, {
            "cityId": 11271,
            "cityName": "桐城",
            "listName": "tc"
        }, {
            "cityId": 11288,
            "cityName": "垦利",
            "listName": "kl"
        }, {
            "cityId": 12221,
            "cityName": "义乌",
            "listName": "yw"
        }
        ]
    }
}
//以下方法请勿修改
import Mock from 'mockjs'
import { _searchParam } from 'Api'
import Diff from 'deep-diff'
Mock.mock("http://localhost:3008/citylist", function(option){
    return _searchParam(Diff.diff || Diff.default.diff,option,data)
}).setup({timeout: '200-1000'})